-- Add new AuditAction enum values for full system coverage
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PROJECT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PROJECT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PROJECT_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PROJECT_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TASK_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TASK_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TASK_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MILESTONE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MILESTONE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MILESTONE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_CANCELLED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'UPSKILL_ASSIGNED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'UPSKILL_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'UPSKILL_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'UPSKILL_PROGRESS_LOGGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'UPSKILL_SUBMITTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'UPSKILL_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'UPSKILL_REJECTED';

-- Add new AuditEntity enum values
ALTER TYPE "AuditEntity" ADD VALUE IF NOT EXISTS 'PROJECT';
ALTER TYPE "AuditEntity" ADD VALUE IF NOT EXISTS 'TASK';
ALTER TYPE "AuditEntity" ADD VALUE IF NOT EXISTS 'MILESTONE';
ALTER TYPE "AuditEntity" ADD VALUE IF NOT EXISTS 'LEAVE_REQUEST';
ALTER TYPE "AuditEntity" ADD VALUE IF NOT EXISTS 'UPSKILL_ASSIGNMENT';
